dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

stages:
  - test

jobs:
  include:
    - stage: test
      install: npm install
      script:
        - npm run lint
    - stage: test
      install: npm install
      script:
        - npm test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
